site_name: Maze Studio
theme:
  name: material
  palette: 
    primary: grey
    accent: deep orange
    scheme: default
  features:
    - toc.integrate
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.path
    - navigation.expand
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - glightbox
  - search

nav:
  - Home: index.md
  - Projects:
    - Getting Started: projects/index.md
    - Owned Project:
      - 65XT: projects/65xt.md
      - Avelia: projects/avelia.md
      - Option719: projects/option719.md
    - Commission:
      - Stellar60: projects/stellar60.md



    
